### ISSUE TITLE
Bundle configuration documentation outdated 

### ISSUE THREAD

**Issue by vincentlepot** [Tisseo/PaonBundle#1]
When installing paon with the configuration described in the README, the kernel refuses to boot.

I succeeded to boot it using a block like this one:

``` yaml
tisseo_paon:
    data_exchange:
        jenkins_server: 'localhost'
        jenkins_users:
            - { profile: 'admin', user: 'admin' }
            - { profile: 'iv', user: 'iv' }
        jobs:
            master_prefix:  'master'
            atomic_prefix:  'atomic'
    mailer:
        default_email_dest: [ 'user@foo.bar' ]
        default_email_exp:  'paon@foo.bar'
```
